### ISSUE TITLE
Ignores dbt column quote setting

### ISSUE THREAD

**Issue by fharrell-tfin** [infinitelambda/dbt-tags#28]
### Describe the bug
The quote: parameter for the column is ignored.

```
sources:
- name: fake_model
  columns:
    - name: fakeColumn
      quote: true
      tags:
         - fake_tag
```

Generates:
```
alter table fake_database.fake_schema.fake_model alter column fakecolumn set tag...
```

Results:
Invalid identifier error when "fakeColumn" is the name in Snowflake.

Using snowflake on dbt cloud
