### ISSUE TITLE
JavaScript analytics write key detected

### ISSUE THREAD

**Issue by suladance** [infinitelambda/dbt-tags#29]
### Describe the bug

Both GitHub Copilot Secret Scanning and Opsera GitCustodian have picked up a secret in the docs/ directory in this file: dbt_packages/dbt_tags/docs/assets/js/custom.js
Line 150 and 151.

### Steps to reproduce

1. Add dbt_tags package to project with dbt deps
2. Run GitHub Copilot Secret Scanning
3. Secret scanning alert triggered

### System information

**The contents of your `packages.yml` file:**
```
packages:
  - package: dbt-labs/dbt_utils
    version: 1.3.0
  - package: dbt-labs/codegen
    version: 0.13.1
  - package: infinitelambda/dbt_tags
    version: 1.4.0
  - package: fivetran/salesforce_formula_utils
    version: 0.10.0
```

**Which database are you using dbt with?**
Snowflake

**The output of `dbt --version`:**
dbt Cloud: Latest

### Additional context

Previously opened a security remediation related to Ospera GitCustodian but closed due to internal resolution, issue occurring again.
