### ISSUE TITLE
Support dbt identifier quoting for the source tables

### ISSUE THREAD

**Issue by joshuanits** [infinitelambda/dbt-tags#32]
### Describe the bug
Similar to https://github.com/infinitelambda/dbt-tags/issues/28, but for the identifier (and database/schema presumably).

https://docs.getdbt.com/reference/resource-properties/quoting

### Steps to reproduce
```yml
sources:
  - name: fake_source
    quoting:
      identifier: true
    tables:
      - name: fake_table
        columns:
          - name: fakeColumn
            quote: true
            tags: fake_tag
```

### Expected results
```sql
alter table fake_database.fake_schema."fakeTable"
            alter column "fakeColumn"
            set tag ...;
```

### Actual results
```sql
alter table fake_database.fake_schema.fakeTable
            alter column "fakeColumn"
            set tag ...;
```

### System information

**The contents of your `packages.yml` file:**

**Which database are you using dbt with?**

- [x] snowflake
- [ ] other (specify: ____________)

**The output of `dbt --version`:**

```log
Core:
  - installed: 1.9.3
  - latest:    1.9.4 - Update available!

  Your version of dbt-core is out of date!
  You can find instructions for upgrading here:
  https://docs.getdbt.com/docs/installation

Plugins:
  - snowflake: 1.9.2 - Update available!

  At least one plugin is out of date with dbt-core.
  You can find instructions for upgrading here:
  https://docs.getdbt.com/docs/installation
```

### Are you interested in contributing the fix?
Sure :)
